services:
  assessment-view-api:
    build:
      context: .
      target: development
    networks:
      - hmpps
    depends_on:
      - postgres
      - coordinator-api
      - aap-api
    command: gradle --parallel --build-cache bootRun
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
      interval: 5s
      retries: 100
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: api,dev
      HMPPS_AUTH_URL: http://hmpps-auth:9090/auth
      DATABASE_ENDPOINT: postgres:5432
      COORDINATOR_API_BASE_URL: http://coordinator-api:8080
      AAP_API_BASE_URL: http://aap-api:8080

  coordinator-api:
    image: ghcr.io/ministryofjustice/hmpps-assess-risks-and-needs-coordinator-api:latest
    networks:
      - hmpps
    depends_on:
      - postgres
      - hmpps-auth
    healthcheck:
      test: ["CMD", "curl", "-f", "http://coordinator-api:8080/health/ping"]
      interval: 5s
      retries: 100
    environment:
      SERVER_PORT: 8080
      APP_DB_ENDPOINT: postgres:5432
      HMPPS_AUTH_BASE_URL: http://hmpps-auth:9090/auth
      CLIENT_ID: hmpps-assess-risks-and-needs-oastub-ui
      CLIENT_SECRET: clientsecret
      SAN_API_BASE_URL: http://localhost:8080
      SP_API_BASE_URL: http://localhost:8080

  aap-api:
    image: ghcr.io/ministryofjustice/hmpps-arns-assessment-platform-api:latest
    networks:
      - hmpps
    depends_on:
      - postgres
      - hmpps-auth
    healthcheck:
      test: ["CMD", "curl", "-f", "http://aap-api:8080/health/ping"]
      interval: 5s
      retries: 100
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dev,postgres
      DATABASE_ENDPOINT: postgres:5432
      HMPPS_AUTH_URL: http://hmpps-auth:9090/auth

  postgres:
    image: postgres:16
    networks:
      - hmpps
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: root
    tmpfs:
      - /var/lib/postgresql

  hmpps-auth:
    image: ghcr.io/ministryofjustice/hmpps-auth:2026-03-02.422.c36796f
    networks:
      - hmpps
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hmpps-auth:9090/auth/health"]
      interval: 5s
      retries: 100
    environment:
      SERVER_PORT: 9090
      SPRING_PROFILES_ACTIVE: dev
      APPLICATION_AUTHENTICATION_UI_ALLOWLIST: 0.0.0.0/0

networks:
  hmpps:
