generic-service:
  nameOverride: hmpps-arns-assessment-view-api
  productId: "HMPPS509" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-arns-assessment-view-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-arns-assessment-view-api-cert

  # Environment variables to load into the deployment
  env:
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "api"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-arns-assessment-view-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"

    rds-arns-assessment-view-instance-output:
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_NAME: "database_name"
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-arns-assessment-view-api

syncCronjob:
  enabled: true
  schedule: "0 */6 * * *"
  suspend: false
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  restartPolicy: Never
  alerting:
    enabled: false
