info.app:
  name: HMPPS Arns Assessment View Api
  version: 1.0

spring:
  application:
    name: hmpps-arns-assessment-view-api

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${hmpps-auth.url}/.well-known/jwks.json

      client:
        provider:
          hmpps-auth:
            token-uri: ${hmpps-auth.url}/oauth/token

  http:
    codecs:
      max-in-memory-size: 10MB

  web:
    error:
      include-message: always