services:
  assessment-view-api:
    build:
      target: development
    command: gradle --parallel --build-cache bootRun
    volumes:
      - ../.git:/app/.git
      - ../.gradle:/home/gradle/.gradle
      - ../build:/app/build
      - ../src:/app/src
      - ../build.gradle.kts:/app/build.gradle.kts
      - ../settings.gradle.kts:/app/settings.gradle.kts

volumes:
  .gradle:
  build:
