services:
  postgres:
    ports:
      - "5432:5432"

  hmpps-auth:
    ports:
      - "9090:9090"

  assessment-view-api:
    ports:
      - "8080:8080"
      - "5005:5005"

  aap-api:
    ports:
      - "8090:8080"

  coordinator-api:
    ports:
      - "6060:8080"

  localstack:
    ports:
      - "4566:4566"