services:
  assessment-view-api:
    build:
      context: ..
      target: development
    networks:
      - hmpps
    depends_on:
      - postgres
      - coordinator-api
      - aap-api
      - localstack
    command: gradle --parallel --build-cache bootRun
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
      interval: 5s
      retries: 100
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dev,coordinator-queue
      HMPPS_AUTH_URL: http://hmpps-auth:9090/auth
      DATABASE_ENDPOINT: postgres:5432
      COORDINATOR_API_BASE_URL: http://coordinator-api:8080
      AAP_API_BASE_URL: http://aap-api:8080
      API_CLIENT_ID: hmpps-arns-assessment-view-api
      API_CLIENT_SECRET: clientsecret
      HMPPS_SQS_PROVIDER: localstack
      HMPPS_SQS_LOCALSTACK_URL: http://localstack:4566
      HMPPS_SQS_QUEUES_COORDINATOR_QUEUE_NAME: coordinator-queue
      COORDINATOR_EVENT_LISTENER_ENABLED: "true"

  localstack:
    image: localstack/localstack:4
    networks:
      - hmpps
    healthcheck:
      test: ["CMD", "bash", "/scripts/wait/healthcheck.sh"]
      interval: 5s
      timeout: 10s
      retries: 50
    volumes:
      - "./scripts/localstack/init:/etc/localstack/init/ready.d"
      - "./scripts/localstack/wait:/scripts/wait"
    environment:
      - SERVICES=sqs
      - LOCALSTACK_HOST=localstack:4566
      - DEFAULT_REGION=eu-west-2
      - AWS_DEFAULT_REGION=eu-west-2
      - USE_SSL=false

  coordinator-api:
    image: ghcr.io/ministryofjustice/hmpps-assess-risks-and-needs-coordinator-api:latest
    networks:
      - hmpps
    depends_on:
      - postgres
      - hmpps-auth
    healthcheck:
      test: ["CMD", "curl", "-f", "http://coordinator-api:8080/health/ping"]
      interval: 5s
      retries: 100
    environment:
      SERVER_PORT: 8080
      APP_DB_ENDPOINT: postgres:5432
      HMPPS_AUTH_BASE_URL: http://hmpps-auth:9090/auth
      CLIENT_ID: hmpps-assess-risks-and-needs-oastub-ui
      CLIENT_SECRET: clientsecret
      SAN_API_BASE_URL: http://localhost:8080
      SP_API_BASE_URL: http://localhost:8080
      AAP_API_BASE_URL: http://aap-api:8080

  aap-api:
    image: ghcr.io/ministryofjustice/hmpps-arns-assessment-platform-api:latest
    networks:
      - hmpps
    depends_on:
      - postgres
      - hmpps-auth
    healthcheck:
      test: ["CMD", "curl", "-f", "http://aap-api:8080/health/ping"]
      interval: 5s
      retries: 100
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dev,postgres
      DATABASE_ENDPOINT: postgres:5432
      HMPPS_AUTH_URL: http://hmpps-auth:9090/auth

  postgres:
    image: postgres:16
    networks:
      - hmpps
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: root
    tmpfs:
      - /var/lib/postgresql
    volumes:
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh

  hmpps-auth:
    image: ghcr.io/ministryofjustice/hmpps-auth:latest
    networks:
      - hmpps
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9090"]
      interval: 5s
      retries: 100
    volumes:
      - ./hmpps-auth-seed:/custom-db
    environment:
      SERVER_PORT: 9090
      SPRING_PROFILES_ACTIVE: dev,local-postgres
      APPLICATION_AUTHENTICATION_UI_ALLOWLIST: 0.0.0.0/0
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_FLYWAY_LOCATIONS: classpath:db/auth,db/auth_postgresql,db/dev/data/auth_postgresql,db/dev/data/auth,filesystem:/custom-db

networks:
  hmpps:
