---
# Per environment values which override defaults in hmpps-arns-assessment-view-api/values.yaml

generic-service:
  ingress:
    host: arns-assessment-view-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    COORDINATOR_API_BASE_URL: "https://arns-coordinator-api.hmpps.service.justice.gov.uk"
    AAP_API_BASE_URL: "https://arns-assessment-platform-api.hmpps.service.justice.gov.uk"
    SYNC_ENABLED: "true"
    SYNC_INTERVAL_MINUTES: 5

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-arns-prod